name: Build and push dripline-cpp Images

on:
  push:
    branches: [ main, develop, feature/ghactions ]
    tags: 'v*.*.*'

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      #- name: Build the Docker image
      #  run: docker build . --file Dependencies/Dockerfile --tag p8compute_dependencies:test
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: Dependencies/
          file: Dependencies/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: driplineorg/dripline-cpp:gha_test  # todo: how to make this depend on the tag for releases
          platforms: linux/amd64 #,linux/arm7,linux/arm64
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
