# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"
  apt_packages:
    - doxygen
    - graphviz
  jobs:
    pre_build:
      - git submodule update --init --recursive
      - python ./documentation/source/pre_doxygen.py
      - env
      - pwd
      - tree
      - doxygen ./scarab/documentation/cpp/Doxyfile
      - mkdir -p $READTHEDOCS_OUTPUT/html
      - mv ./user_doxygen_out/html $READTHEDOCS_OUTPUT/html/_static

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: documentation/source/conf.py

submodules:
  recursive: true

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# python:
#    install:
#    - requirements: docs/requirements.txt
