version: '2'

services:
    # a rabbit broker
    rabbit_broker:
        image: rabbitmq:3-management
        ports:
          - "127.0.0.1:8888:15672"
        ports:
          - "5672:5672"
          - "15672:15672"
